import pandas as pd
import numpy as np

# Load the test predictions and residuals generated by the ML pipeline
df = pd.read_csv("data/processed/test_residuals.csv")

print("Analytics dataset loaded successfully.")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
print(df.head())

# Calculate absolute prediction error
df["absolute_error"] = np.abs(df["residual"])

print("\nAbsolute error calculated successfully.")
print(df[["y_true", "y_pred", "residual", "absolute_error"]].head())

# Identify over-predictions and under-predictions
df["over_predicted"] = df["residual"] < 0
df["under_predicted"] = df["residual"] > 0

print("\nPrediction direction:")
print(df[["y_true", "y_pred", "residual",
          "over_predicted", "under_predicted"]].head())

# Calculate prediction direction percentages
over_prediction_rate = df["over_predicted"].mean() * 100
under_prediction_rate = df["under_predicted"].mean() * 100

print("\nPrediction Direction KPIs:")
print(f"Over-prediction rate: {over_prediction_rate:.2f}%")
print(f"Under-prediction rate: {under_prediction_rate:.2f}%")