import pandas as pd
import numpy as np

# Load the test predictions and residuals generated by the ML pipeline
df = pd.read_csv("data/processed/test_residuals.csv")

print("Analytics dataset loaded successfully.")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
print(df.head())
